# ----------------------------------------
# YAML 1: .NET Application CI/CD Pipeline (Inline values)
# ----------------------------------------
trigger:
- main  # Trigger pipeline when code is pushed to 'main' branch

stages:
- stage: Build
  displayName: "Build Stage"
  jobs:
  - job: Build
    displayName: "Build .NET Application"
    pool:
      vmImage: 'windows-latest'  # Using Windows agent for .NET
    steps:
    - task: UseDotNet@2  # Install .NET SDK
      inputs:
        packageType: 'sdk'
        version: '6.x'  # Specify .NET SDK version

    - task: DotNetCoreCLI@2
      displayName: Restore dependencies
      inputs:
        command: 'restore'
        projects: '**/*.csproj'

    - task: DotNetCoreCLI@2
      displayName: Build the project
      inputs:
        command: 'build'
        projects: '**/*.csproj'
        arguments: '--configuration Release'

    - task: DotNetCoreCLI@2
      displayName: Publish the project
      inputs:
        command: 'publish'
        projects: '**/*.csproj'
        arguments: '--configuration Release --output $(Build.ArtifactStagingDirectory)'
        zipAfterPublish: true

    - task: PublishBuildArtifacts@1  # Publish build output to DevOps
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: 'drop'
        publishLocation: 'Container'

- stage: Deploy
  displayName: "Deploy Stage"
  dependsOn: Build
  condition: succeeded()
  jobs:
  - job: Deploy
    displayName: "Deploy to Azure Web App"
    pool:
      vmImage: 'windows-latest'
    steps:
    - task: DownloadBuildArtifacts@1  # Download previously published artifacts
      inputs:
        buildType: 'current'
        downloadType: 'single'
        artifactName: 'drop'
        downloadPath: '$(System.ArtifactsDirectory)'

    - task: AzureWebApp@1  # Deploy to Azure Web App
      inputs:
        azureSubscription: 'Tech Tutorials With Piyush (9e9c27ce-e0c8-4171-a368-ad16977ec849)'
        appType: 'webApp'
        appName: 'TechTutorialsWithPiyush'
        package: '$(System.ArtifactsDirectory)/drop/**/*.zip'

# ----------------------------------------
# YAML 2: .NET Application CI/CD using Variables
# ----------------------------------------

trigger:
- main

variables:
  vmImage: 'windows-latest'  # Pool image
  buildConfig: 'Release'  # .NET build configuration
  projectFile: '**/*.csproj'
  artifactName: 'drop'
  azureSub: 'Tech Tutorials With Piyush (9e9c27ce-e0c8-4171-a368-ad16977ec849)'
  appName: 'TechTutorialsWithPiyush'

stages:
- stage: Build
  displayName: 'Build Stage'
  jobs:
  - job: Build
    displayName: 'Build .NET App'
    pool:
      vmImage: $(vmImage)
    steps:
    - task: UseDotNet@2
      inputs:
        packageType: 'sdk'
        version: '6.x'

    - task: DotNetCoreCLI@2
      displayName: Restore
      inputs:
        command: 'restore'
        projects: $(projectFile)

    - task: DotNetCoreCLI@2
      displayName: Build
      inputs:
        command: 'build'
        projects: $(projectFile)
        arguments: '--configuration $(buildConfig)'

    - task: DotNetCoreCLI@2
      displayName: Publish
      inputs:
        command: 'publish'
        projects: $(projectFile)
        arguments: '--configuration $(buildConfig) --output $(Build.ArtifactStagingDirectory)'
        zipAfterPublish: true

    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: $(artifactName)
        publishLocation: 'Container'

- stage: Deploy
  displayName: 'Deploy Stage'
  dependsOn: Build
  condition: succeeded()
  jobs:
  - job: Deploy
    displayName: 'Deploy to Azure Web App'
    pool:
      vmImage: $(vmImage)
    steps:
    - task: DownloadBuildArtifacts@1
      inputs:
        buildType: 'current'
        downloadType: 'single'
        artifactName: $(artifactName)
        downloadPath: '$(System.ArtifactsDirectory)'

    - task: AzureWebApp@1
      inputs:
        azureSubscription: $(azureSub)
        appType: 'webApp'
        appName: $(appName)
        package: '$(System.ArtifactsDirectory)/$(artifactName)/**/*.zip'
