name: .NET Build and Run

on:
  push:
    branches: [ main ]     # Run on push to main
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest  # GitHub-hosted Ubuntu runner

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'  # Use .NET 8 (or change to 6.0, 7.0, etc.)

    - name: Restore dependencies
      run: dotnet restore

    - name: 🛠️ Build the app
      run: dotnet build --configuration Release

    - name: Run the app
      run: dotnet run --project ./HelloWorldDotNet.csproj
