apiVersion: v1
kind: Service
metadata:
  name: nginx-clusterip
  namespace: dev
spec:
  type: ClusterIP  # Default service type; internal communication only
  selector:
    app: nginx  # Matches the app label in the Deployment
  ports:
    - port: 80         # Port exposed inside the cluster
      targetPort: 80   # Port on the container
      protocol: TCP
