apiVersion: v1
kind: Service
metadata:
  name: nginx-external
  namespace: dev
spec:
  type: ExternalName  # Redirects to an external DNS
  externalName: example.com  # Resolves nginx-external.dev to example.com
