apiVersion: v1
kind: Service
metadata:
  name: nginx-loadbalancer
  namespace: dev
spec:
  type: LoadBalancer  # Requests a public IP (simulated by Docker Desktop)
  selector:
    app: nginx
  ports:
    - port: 80         # Service port
      targetPort: 80   # Container port
      protocol: TCP
