pipeline {
    agent any

    environment {
        IMAGE_NAME = "hello-docker:latest"
    }

    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Build Docker Image') {
            steps {
                sh 'docker build -t ${IMAGE_NAME} .'
            }
        }

        stage('Run Docker Image') {
            steps {
                sh 'docker run -d -p 3000:3000 --name hello-container ${IMAGE_NAME}'
            }
        }

        stage('Verify Container') {
            steps {
                sh 'curl --retry 5 --retry-delay 2 http://localhost:3000'
            }
        }
    }

    post {
        always {
            echo '🧹 Cleaning up container...'
            sh 'docker stop hello-container || true'
            sh 'docker rm hello-container || true'
        }
        success {
            echo '✅ Hello Docker pipeline completed successfully!'
        }
        failure {
            echo '❌ Pipeline failed.'
        }
    }
}
