# pod-anti-affinity.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pod-with-anti-affinity
spec:
  replicas: 2
  selector:
    matchLabels:
      app: anti-affinity-demo
  template:
    metadata:
      labels:
        app: anti-affinity-demo
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: "app"
                    operator: In
                    values:
                      - anti-affinity-demo
              topologyKey: "kubernetes.io/hostname"  # Prevent pods from running on the same node
      containers:
        - name: nginx
          image: nginx
